default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: adtsys_applicant_development

test: &test
  <<: *default
  database: adtsys_applicant_test

production:
  <<: *default
  database: adtsys_applicant_production
  username: adtsys_applicant
  password: <%= ENV['ADTSYS_APPLICANT_DATABASE_PASSWORD'] %>
